name: Build APK Cinema BRtv

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Find and unzip project
        run: |
          ZIP_FILE=$(ls *.zip | head -n 1)
          echo "Using ZIP: $ZIP_FILE"
          unzip "$ZIP_FILE"
          PROJECT_DIR=$(find . -name gradlew -type f | sed 's|/gradlew||')
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Gradle permission
        run: chmod +x $PROJECT_DIR/gradlew

      - name: Build Debug APK
        run: |
          cd $PROJECT_DIR
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CinemaBRtv-APK
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
