name: Build APK Cinema BRtv

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip project
        run: |
          ZIP_FILE=$(ls *.zip | head -n 1)
          unzip "$ZIP_FILE"
          ROOT_DIR=$(ls -d */ | head -n 1)
          echo "ROOT_DIR=$ROOT_DIR" >> $GITHUB_ENV

      - name: Show extracted files (debug)
        run: |
          echo "Root dir:"
          ls -la
          echo "Inside root:"
          ls -la $ROOT_DIR

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK
        run: |
          cd $ROOT_DIR
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CinemaBRtv-APK
          path: ${{ env.ROOT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
